---
engines:
    coverage:
        enabled: true
    metrics:
        enabled: true

exclude_paths:
    - '.codacy.yml'
    - '.gitignore'
    - '.bundle/**'
    - 'spec/**/*'
    - 'benchmarks/**/*'
    - '**.min.js'
    - 'source/build/**'
    - 'source/js/tests/**'
    - 'docs/**'
    - 'specs/**'
    - 'CI/**'
    - 'admin/**'
    - '.github/**'
    - 'reports/**'
