name: Build

on:
    push:
        branches:
            - main
        paths:
            - "source/**"
            - ".github/**"
    pull_request:
        branches:
            - main
        paths:
            - "source/**"
            - ".github/**"

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - name: Fetch Code
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Intall modules
              run: |
                  cd source
                  npm i webpack
                  npm i -D webpack-cli
                  npm i --save-dev jest babel-jest @babel/core @babel/preset-env
            - name: Build
              run: |
                  cd source
                  npm run build_js
            - name: Testing
              run: |
                  cd source
                  npm test
