name: Build

on:
    push:
        branches:
            - main
            - develop
        paths:
            - "source/**"
            - ".github/**"
    pull_request:
        branches:
            - main
            - develop
        paths:
            - "source/**"
            - ".github/**"

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - name: Fetch Code
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Intall modules
              run: |
                  cd source
                  npm i webpack
                  npm i -D webpack-cli
                  npm i -D jest
                  npm run build
                  npm run build_test
            - name: Testing
              run: |
                  cd source
                  npm test
            - name: Push artifact
              uses: EndBug/add-and-commit@v7
              with:
                  author_name: github
                  message: "Update build"
                  add: "source/build/*"
