name: Generate Documentations

on:
    push:
        branches:
            - main
        paths:
            - "source/**"
    pull_request:
        branches:
            - main
        paths:
            - "source/**"

jobs:
    gendoc:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [10.x, 12.x]

        steps:
            - name: Fetch Code
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Intall modules
              run: |
                  cd source
                  npm i -g jsdoc
            - name: Generating
              run: |
                  cd source
                  npm run doc
            - name: Show result
              run: |
                  cd docs
                  ls
