name: lint

on:
    push:
        branches:
            - main
            - develop
        paths:
            - 'source/**'
            - '.github/**'
    pull_request:
        branches:
            - main
            - develop
        paths:
            - 'source/**'
            - '.github/**'

jobs:
    super-lint:
        name: Lint Code Base
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Run Linter
              uses: github/super-linter@v3
              env:
                  DEFAULT_BRANCH: main
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  IGNORE_GITIGNORED_FILES: true
                  DISABLE_ERRORS: true
                  VALIDATE_ALL_CODEBASE: false
                  JAVASCRIPT_DEFAULT_STYLE: prettier
                  FILTER_REGEX_EXCLUDE: source/build/**
                  FILTER_REGEX_INCLUDE: source/**
        