name: lint

on: 
  push:
    branches:
      - main
      - develop 
    paths:
      - 'source/**'
      - '.github/**'
  pull_request:
    branches:
      - main
      - develop 
    paths:
      - 'source/**'
      - '.github/**'

jobs: 
  
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Remove files
        run: |
          echo 'path:'
          pwd
          ls ./
          chmod a+x ./scripts/rm_others.sh
          ./scripts/rm_others.sh
          ls ./
      - name: Run Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
