name: lint

on:
    push:
        branches:
            - main
            - develop
        paths:
            - 'source/**'
            - '.github/**'
    pull_request:
        branches:
            - main
            - develop
        paths:
            - 'source/**'
            - '.github/**'

jobs:
    super-lint:
        name: Lint Code Base
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Run Linter
              uses: github/super-linter@v3
              env:
                  DEFAULT_BRANCH: main
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  IGNORE_GITIGNORED_FILES: true
                  DISABLE_ERRORS: false
                  VALIDATE_ALL_CODEBASE: true
                  VALIDATE_JAVASCRIPT_STANDARD: false
                  FILTER_REGEX_EXCLUDE: source/build/**
                  FILTER_REGEX_INCLUDE: source/**
    prettier:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  # Make sure the actual branch is checked out when running on pull requests
                  ref: ${{ github.head_ref }}
           - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Intall modules
              run: |
                  cd source
                  npm i --save-dev --save-exact prettier
                  npx prettier --find-config-path ./prettierrc --ignore-path ./prettierignore --check .
                
        
